version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo Installing codebuild-extras...
      - curl -fsSL https://raw.githubusercontent.com/thii/aws-codebuild-extras/fd64ace08a309109058c461e6997807e7473fc61/install >> extras.sh
      - . ./extras.sh

  pre_build:
    commands:
      - echo $CODEBUILD_GIT_BRANCH
      - pip install --upgrade pip
      - ls
      - pwd
      - pip install -r test/requirements.txt
      - export PYTHONPATH=$PWD/src/library:$PWD/src:$PYTHONPATH
      - python -m pytest tests

  build:
    commands:
      - sam build

  post_build:
    commands:
      - sam package --output-template-file packaged.yaml --s3-bucket sam-codedeploy-package

artifacts:
  type: zip
  files:
    - packaged.yaml