version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7

  pre_build:
    commands:
      - export PYTHONPATH=$PWD/src/library:$PWD/src:$PYTHONPATH
      - python3 -m pytest tests

  build:
    commands:
      - sam build

  post_build:
    commands:
      - sam package --output-template-file packaged.yaml --s3-bucket sam-codedeploy-package

artifacts:
  type: zip
  files:
    - packaged.yaml