version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "reel"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-181l9cnqda9df"
s3_prefix = "reel"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
